config/routes.rb
Quotes::Application.routes.draw do
  get "login" => "sessions#new"
  post "login" => "sessions#create"
  post "search" => "search#create"

  get "upvote/:id" => "upvotes#upvote", as: "upvote"

  resources :users do
    resources :quotes
  end

  resources :quotes, only: [:new, :create]

  mount JasmineRails::Engine => "/specs" if defined?(JasmineRails)
end

app/models/quote.rb
class Quote < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :quotes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @_current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController

  def index
    redirect_to :root unless current_user

    @user = User.find(params[:user_id])
    @quotes = @user.quotes.where(published: true)
  end

  def new
    @quote = current_user.quotes.build
  end

  def create
    quote = current_user.quotes.build(create_params)

    if quote.save
      redirect_to user_quotes_path(current_user)
    else
      render :new
    end
  end

  private
  def create_params
    params.require(:quote).permit(:user_id, :body, :author)
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  def create
    @quotes = Quote.where("published = 't' AND body LIKE '%#{params[:search]}%'")

    render :results
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to user_quotes_path(user)
    else
      render :new
    end
  end

  def new

  end
end

app/controllers/upvotes_controller.rb
class UpvotesController < ApplicationController

  def upvote
    quote = Quote.find(params[:id])
    quote.update_attributes(upvotes: quote.upvotes+1)

    respond_to do |format|
      format.json do
        render json: quote
      end

      format.html do
        redirect_to user_quotes_path(current_user)
      end
    end

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Quotes</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="nav">
    <% if current_user %>
      <%= link_to "My Quotes", user_quotes_path(current_user) %>
      <%= link_to "Submit New Quote", new_quote_path %>
    <% end %>

    <%= form_tag search_path do %>
      <%= label_tag :search %>
      <%= text_field_tag :search %>
    <% end %>
  </div>

<%= yield %>

</body>
</html>

app/views/quotes/_quote.html.erb
<div class="callout quote">
  <div class="quote-body">
    <%= quote.body.html_safe %>
  </div>

  <div class="quote-author">
    <%= quote.author %>
  </div>

  <div class="voting">
    <span class="vote-count"><%= quote.upvotes %></span> <%= link_to "Up Vote", upvote_path(quote) %>
  </div>
</div>

app/views/quotes/index.html.erb
<h1>Quotes submitted by <%=@user.email%></h1>

<% @quotes.each do |quote| %>
  <div class="callout quote">
    <div class="quote-body">
      <%= quote.body %>
    </div>

    <div class="quote-author">
      <%= quote.author %>
    </div>
  </div>
<% end %>

app/views/quotes/new.html.erb
<h1>New Quote</h1>

<%= form_for @quote do |f| %>
  <%= f.label :body %><br />
  <%= f.text_area :body %><br />
  <p id="body-length-status">
    <span id="count"></span> characters
  </p>

  <%= f.label :author %><br />
  <%= f.text_field :author %><br />

  <%= f.submit %>
<% end %>

app/views/search/results.html.erb
<h1>Search Results</h1>

<% @quotes.each do |q| %>
  <%= render partial: "quotes/quote", locals: {quote: q} %>
<% end %>

app/views/search/show.html.erb
<%= @image_info %>